### ISSUE TITLE
When Will CR be open again?

### ISSUE THREAD

**Issue by ghost** [customrealms/customrealms.github.io#1]
when will custom realms be open again

**Comment by joakimsii** [comment]
thinking same...

**Comment by falloutxd** [comment]
also thinking the same. i wanna make a plugin but eclipse is not working for me.

**Comment by Stormsquid** [comment]
Yeah I wanted to get into coding, but I was sad when I saw they were down. I hope they come back up soon

**Comment by ghost** [comment]
> also thinking the same. i wanna make a plugin but eclipse is not working for me.

try IntelliJ and watch this YT vid https://www.youtube.com/watch?v=EDCt9RNZDwo btw i didn't make that video

**Comment by connerdouglass** [comment]
Hey everyone. I just released updated versions of the CustomRealms code. Now, you can write a JavaScript plugin and compile it into a JAR file.

It's still hard to use for beginners, but I'll make it a lot more user friendly very soon. My goal is that you'll have a JavaScript project (using npm) and will just run `npm run build` to generate the JAR file. It's pretty close!

Go check out the projects:
https://github.com/customrealms/core
https://github.com/customrealms/bukkit-runtime

**Comment by Voidedglitch** [comment]
I am wondering the same exact question Cant they have it open and work on open sourcing there code?  Just dupe the software if you need the files to be offline

**Comment by BeneUser** [comment]
So I just watched a starters tutorial and thought about beginning with CustomRealms. Has Cr been down now since august? Because then I'll guess it may not be back up for another three months and I don't wanna wait for so long. Then I sadly have to look for another solution, though it seemed so cool and convenient.

**Comment by NoDEV1593** [comment]
Still down...

**Comment by connerdouglass** [comment]
The CustomRealms website from the tutorial videos is no longer available. We'll create some new tutorials soon.
